// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tgkuzmuevhpoovwuargc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRna3V6bXVldmhwb292d3VhcmdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2OTU2ODMsImV4cCI6MjA2NDI3MTY4M30.M0p1Ru4uzmSEHvfqSFMhd-XOZ8F9yocaw2P9Are1--A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});